name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run build script 
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript python3-tk
          pip install -r api/requirements.txt 
          python api/load_model.py
        shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r api/requirements.txt; fi
      - name: Test with pytest      
        uses: dariocurr/pytest-summary@main 
        with:
          output: test-summary.md
          paths: tests/**.py